### ISSUE TITLE
Fix Chat icon

### ISSUE THREAD

**Issue by alexmatz** [urbit/interface#19]
The main chat icon in modulo is missing the dots from the figma mocks and the inconsistent padding on the overlapping part of the icon is uspetting Anthony

**Comment by vvisigoth** [comment]
I am a man of discerning tastes.

![](https://pbs.twimg.com/media/D-3YRP4WsAEm6Jb.jpg)

**Comment by alexmatz** [comment]
thanks for leaving a screenshot @loganallenc

**Comment by g-a-v-i-n** [comment]
Screenshot?

**Comment by alexmatz** [comment]
<img width="252" alt="Screen Shot 2019-07-12 at 1 34 52 PM" src="https://user-images.githubusercontent.com/44714137/61157076-e9c5e680-a4a9-11e9-9b9a-22808f709973.png">

**Comment by g-a-v-i-n** [comment]
I've emailed new assets out

**Comment by tacryt-socryp** [comment]
3e28953a6328666e8736a71392868d46550b5573
