### ISSUE TITLE
Inviting same ship multiple times results in multiple invites

### ISSUE THREAD

**Issue by wkim1** [urbit/interface#2]
See gif:

![ezgif-2-005b4765d224](https://user-images.githubusercontent.com/5248096/59956702-b2ce5900-9446-11e9-96e7-a2acc5f33f8c.gif)

**Comment by tacryt-socryp** [comment]
It now shows feedback on successful invites and clears the textbox. Should be good enough, hard to prevent duplicate invites overall.

**Comment by tacryt-socryp** [comment]
@wkim1

**Comment by tacryt-socryp** [comment]
thanks, closing
