### ISSUE TITLE
Channels not working in Firefox

### ISSUE THREAD

**Issue by vvisigoth** [urbit/interface#22]
<img width="1187" alt="Screenshot 2019-07-11 18 10 39" src="https://user-images.githubusercontent.com/1609955/61095198-563bd980-a407-11e9-9694-173227d67990.png">

**Comment by joemfb** [comment]
Also, I think that mime-type should be `application/javascript`.

**Comment by tacryt-socryp** [comment]
I've updated the mime-type and found the root issue. Channels now work in Firefox. An XML parsing error still occurs in console, but doesn't affect application. Closing this.
