### ISSUE TITLE
Blank chat interface in any room with comets

### ISSUE THREAD

**Issue by matildepark** [urbit/interface#34]
Using `~dopzod/urbit-help` presently gives a blank screen for me.

<img width="1710" alt="Screen Shot 2019-07-23 at 12 13 06 AM" src="https://user-images.githubusercontent.com/20846414/61682249-e408a600-acde-11e9-83ab-d6420f593ebb.png">

The console suggests sigil.js chokes on rendering comets and tanks the display with it:

<img width="2160" alt="Screen Shot 2019-07-23 at 12 14 10 AM" src="https://user-images.githubusercontent.com/20846414/61682275-f551b280-acde-11e9-8ba5-e1be1942dc13.png">

**Comment by ixv** [comment]
fixed: https://github.com/urbit/interface/pull/36
