### ISSUE TITLE
-1 new messages

### ISSUE THREAD

**Issue by iamwillkim** [urbit/interface#5]
![image](https://user-images.githubusercontent.com/14853906/59956968-e14d3380-9448-11e9-8857-d1d82511c4cd.png)

**Comment by tacryt-socryp** [comment]
Fixed. Try out the new implementation and lmk if you think it's good enough in terms of latency. Used a timer instead of the event-based mechanism I was using before. @iamwillkim

**Comment by tacryt-socryp** [comment]
Improved the latency. Marking as fixed.
